function []=RegisterImage(refimage,floatimage,floatsegment,options,appendix)
affine_image=strcat('ref_',refimage(1:7),'_flo_',floatimage(1:4),floatimage(10),'_affine.nii');
affine_matrix=strcat('ref_',refimage(1:7),'_flo_',floatimage(1:4),floatimage(10),'_affine.txt');
nonregit_image=strcat('ref_',refimage(1:7),'_flo_',floatimage(1:4),floatimage(10),'_nrr',appendix,'.nii');
nonregit_image_cpp=strcat('ref_',refimage(1:7),'_flo_',floatimage(1:4),floatimage(10),'_nrr_cpp',appendix,'.nii');
registered_segment=strcat('ref_',refimage(1:7),'_flo_',floatimage(1:4),floatimage(10),'_brain',appendix,'.nii');

dos(sprintf(['ceg_aladin' ...
' -ref ',refimage ...
' -flo ',floatimage ... 
' -res ',affine_image ...
' -aff ',affine_matrix ...
' -speeeeed']))

dos(sprintf(['ceg_f3d ' ...
' -ref ',refimage ...
' -flo ',floatimage ... 
' -res ',nonregit_image ...
' -aff ',affine_matrix ...
' -cpp ',nonregit_image_cpp ...
' ',options]))

dos(sprintf(['ceg_resample ' ...
' -ref ',refimage ...
' -flo ',floatsegment ... 
' -res ',registered_segment ...
' -trans ',nonregit_image_cpp ...
' -inter 0']))

